import { LitElement } from 'lit';
import type { DayCell, Locale, BusinessHours } from '@nexa-calendar/core';
export declare class NxMonthView extends LitElement {
    cells: DayCell[];
    locale: Locale;
    dayMaxEvents: number | boolean;
    showNonCurrentDates: boolean;
    weekends: boolean;
    firstDay: number;
    editable: boolean;
    eventStartEditable: boolean;
    businessHours: BusinessHours | BusinessHours[] | boolean;
    private _popoverCell;
    render(): import("lit").TemplateResult<1>;
    private _renderPopover;
    private _togglePopover;
    private _closePopoverOnOutsideClick;
    private _getWeekdays;
    private _getWeeks;
    private _getVisibleEvents;
    private _isBusinessDay;
    private _formatTime;
    connectedCallback(): void;
    disconnectedCallback(): void;
    private _selectDate;
    private _eventClick;
    private _onEventDragStart;
    private _onDrop;
    protected createRenderRoot(): this;
}
